# Generated by Django 3.1.3 on 2020-11-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_auto_20201128_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='desc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
