# Generated by Django 3.1.3 on 2020-11-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_auto_20201128_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='sitename',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(max_length=100),
        ),
    ]
