# Generated by Django 3.1.3 on 2020-11-29 11:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0007_auto_20201128_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(default='media/default.png', max_length=255, verbose_name='image'),
        ),
    ]
