# Generated by Django 3.1.3 on 2020-11-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0010_auto_20201130_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='desc',
            new_name='description',
        ),
    ]
